In [1]:
import pandas as pd
import numpy as np

In [47]:
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [5]:
df.index

RangeIndex(start=0, stop=9704, step=1)

In [6]:
df['fuel_type'] = df['fuel_type'].str.replace(' ', '_').str.lower()
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,gasoline,All-wheel drive,2.0,12.488369

In [7]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
df['origin'] = df['origin'].str.replace(' ', '_').str.lower()
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,europe,gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,usa,gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,europe,gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,usa,diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,europe,gasoline,All-wheel drive,2.0,12.488369

In [10]:
df_asia = df[
    df['origin'] == 'asia'
]
df_asia.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,asia,diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,asia,diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,asia,diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,asia,gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,asia,gasoline,Front-wheel drive,-1.0,16.077730

In [11]:
df_asia.describe().round(2)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,3247.00,3099.00,3013.00,3247.00,2933.00,3247.00,3072.00,3247.00
mean,200.05,4.01,150.30,3006.29,15.04,2011.49,-0.00,14.97
std,49.29,1.97,30.26,502.43,2.49,6.70,1.05,2.58
min,30.00,0.00,40.00,1223.30,6.40,2000.00,-4.00,6.89
25%,170.00,3.00,130.00,2665.52,13.30,2006.00,-1.00,13.25
50%,200.00,4.00,150.00,2988.59,15.10,2012.00,0.00,15.03
75%,230.00,5.00,171.00,3345.36,16.70,2017.00,1.00,16.73
max,370.00,11.00,245.00,4661.14,22.70,2023.00,4.00,23.76

In [48]:
df['horsepower'].median().round(2)

np.float64(149.0)

In [49]:
most_frequent_horsepower = df['horsepower'].value_counts().index[0]
most_frequent_horsepower

np.float64(152.0)

In [50]:
single_most_frequent = df['horsepower'].mode()
single_most_frequent

0    152.0
Name: horsepower, dtype: float64

In [51]:
df_q6 = df['horsepower'].fillna(152.0)
df_q6.head()

0    159.0
1     97.0
2     78.0
3    152.0
4    140.0
Name: horsepower, dtype: float64

In [52]:
df_q6.median().round(2)

np.float64(152.0)

In [18]:
df_q7 = df_asia[['vehicle_weight', 'model_year']]
df_q7.head()

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [19]:
df_q7 = df_q7.iloc[[0,1,2,3,4,5,6]]
df_q7

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [40]:
X = np.vstack([df_q7.vehicle_weight.values, df_q7.model_year.values])
X

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [42]:
XTX = X.dot(X.T)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [33]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [34]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [38]:
X.T

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [43]:
w_t = (X.T).dot(XTX_inv)
w_t

array([[-1.31202622e-04,  2.62636846e-04],
       [-8.63909858e-05,  1.96990690e-04],
       [ 3.72634923e-04, -4.73392228e-04],
       [-4.02726650e-04,  6.58944477e-04],
       [-1.62513724e-04,  3.08357831e-04],
       [-5.52342829e-05,  1.51636137e-04],
       [ 4.65094049e-04, -6.07979633e-04]])

In [45]:
w = y.dot(w_t)
w

array([0.01386421, 0.5049067 ])

In [46]:
w.sum()

np.float64(0.5187709081074026)